---
harbor_version: 2.8.2
harbor_download_url: "https://github.com/goharbor/harbor/releases/download/v{{ harbor_version }}/harbor-offline-installer-v{{ harbor_version }}.tgz"

#harbor_url: ""
#lets_encrypt_email: ""
#harbor_admin_password: ""
#harbor_database_password: ""

harbor_download_dir: "/home/{{ ansible_user }}"
harbor_dir: "{{ harbor_download_dir }}/harbor"

harbor_http_port: 8880
harbor_https_port: 4433

harbor_certificate: "/etc/letsencrypt/live/{{ harbor_url }}/fullchain.pem"
harbor_private_key: "/etc/letsencrypt/live/{{ harbor_url }}/privkey.pem"

harbor_data_volume: "/data"